
import { Book, OrderWithItems, Wish } from '../types';

export const BOOKS: Book[] = [
  {
    id: "1",
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafon",
    genre: "Mystery",
    list_price_cents: 1899,
    isbn13: "9780143126393",
    description: "A sweeping tale of murder, mystery, and obsessive love set in post-Spanish Civil War Barcelona.",
    stock: 15,
    cover_url: "https://picsum.photos/seed/shadow/400/600",
    condition: "New",
    location: "Shelf A-1",
    tags: ["historical", "barcelona", "books about books"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    list_price_cents: 2250,
    isbn13: "9780441013593",
    description: "The story of Paul Atreides, a brilliant young man born into a great destiny, who must travel to the most dangerous planet in the universe.",
    stock: 10,
    cover_url: "https://picsum.photos/seed/dune/400/600",
    condition: "New",
    location: "Shelf S-2",
    tags: ["epic", "space", "politics"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "3",
    title: "Circe",
    author: "Madeline Miller",
    genre: "Fantasy",
    list_price_cents: 1699,
    isbn13: "9780316556347",
    description: "A feminist retelling of the Greek myth of Circe, the powerful witch banished to a remote island.",
    stock: 20,
    cover_url: "https://picsum.photos/seed/circe/400/600",
    condition: "New",
    location: "Table 1",
    tags: ["mythology", "greek", "witch"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "4",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Classic",
    list_price_cents: 1200,
    isbn13: "9780141439518",
    description: "The timeless story of Elizabeth Bennet and her complex relationship with the proud Mr. Darcy.",
    stock: 30,
    cover_url: "https://picsum.photos/seed/pride/400/600",
    condition: "Good",
    location: "Bin 12",
    tags: ["romance", "classic", "england"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "5",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Thriller",
    list_price_cents: 2000,
    isbn13: "9781250301697",
    description: "A shocking psychological thriller of a woman's act of violence against her husband.",
    stock: 8,
    cover_url: "https://picsum.photos/seed/patient/400/600",
    condition: "New",
    location: "Shelf T-4",
    tags: ["psychological", "twist", "murder"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "6",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    list_price_cents: 2500,
    isbn13: "9780062316097",
    description: "A groundbreaking narrative of humanity's creation and evolution.",
    stock: 12,
    cover_url: "https://picsum.photos/seed/sapiens/400/600",
    condition: "New",
    location: "Shelf N-1",
    tags: ["history", "anthropology", "science"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "7",
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Sci-Fi",
    list_price_cents: 2199,
    isbn13: "9780593135204",
    description: "A lone astronaut must save the earth from disaster in this cinematic thriller.",
    stock: 18,
    cover_url: "https://picsum.photos/seed/hailmary/400/600",
    condition: "New",
    location: "Shelf S-3",
    tags: ["space", "survival", "science"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "8",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Mystery",
    list_price_cents: 1800,
    isbn13: "9780735219090",
    description: "A heartbreaking coming-of-age story and a surprising tale of possible murder.",
    stock: 25,
    cover_url: "https://picsum.photos/seed/crawdads/400/600",
    condition: "Very Good",
    location: "Bin 5",
    tags: ["nature", "mystery", "marsh"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "10",
    title: "1984",
    author: "George Orwell",
    genre: "Classic",
    list_price_cents: 1150,
    isbn13: "9780451524935",
    description: "A dystopian novel set in a totalitarian society under the constant surveillance of Big Brother.",
    stock: 40,
    cover_url: "https://picsum.photos/seed/1984/400/600",
    condition: "Acceptable",
    location: "Bin 99",
    tags: ["dystopian", "politics", "classic"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "12",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    list_price_cents: 2700,
    isbn13: "9780735211292",
    description: "An easy & proven way to build good habits & break bad ones.",
    stock: 22,
    cover_url: "https://picsum.photos/seed/atomic/400/600",
    condition: "New",
    location: "Shelf H-1",
    tags: ["productivity", "psychology", "growth"],
    supply_source: "local",
    currency: "USD",
    is_active: true,
    created_at: "2023-01-01T00:00:00.000Z",
    updated_at: "2023-01-01T00:00:00.000Z",
  }
];

export const GENRES = ["Fiction", "Mystery", "Sci-Fi", "Fantasy", "Classic", "Thriller", "Non-Fiction", "Self-Help", "Biography", "Young Adult", "Horror"];

export const MOCK_ORDERS: OrderWithItems[] = [
  {
    id: "ORD-12345",
    created_at: "2023-10-15T00:00:00.000Z",
    status: "Delivered",
    currency: "USD",
    email: "customer@example.com",
    subtotal_cents: 3948,
    tax_cents: 351,
    shipping_cents: 0,
    total_cents: 4299,
    stripe_checkout_session_id: null,
    stripe_payment_intent_id: null,
    user_id: null,
    items: [
      {
        id: "ORD-ITEM-1",
        order_id: "ORD-12345",
        book_id: BOOKS[6].id,
        quantity: 1,
        title: BOOKS[6].title,
        unit_price_cents: BOOKS[6].list_price_cents ?? 0,
        created_at: "2023-10-15T00:00:00.000Z",
      },
      {
        id: "ORD-ITEM-2",
        order_id: "ORD-12345",
        book_id: BOOKS[2].id,
        quantity: 1,
        title: BOOKS[2].title,
        unit_price_cents: BOOKS[2].list_price_cents ?? 0,
        created_at: "2023-10-15T00:00:00.000Z",
      },
    ],
  },
  {
    id: "ORD-67890",
    created_at: "2023-11-01T00:00:00.000Z",
    status: "Shipped",
    currency: "USD",
    email: "reader@example.com",
    subtotal_cents: 2000,
    tax_cents: 0,
    shipping_cents: 0,
    total_cents: 2000,
    stripe_checkout_session_id: null,
    stripe_payment_intent_id: null,
    user_id: null,
    items: [
      {
        id: "ORD-ITEM-3",
        order_id: "ORD-67890",
        book_id: BOOKS[4].id,
        quantity: 1,
        title: BOOKS[4].title,
        unit_price_cents: BOOKS[4].list_price_cents ?? 0,
        created_at: "2023-11-01T00:00:00.000Z",
      },
    ],
  },
];

export const MOCK_WISHES: Wish[] = [
    {
        id: "WISH-001",
        age: 8,
        interests: "Animals, especially dogs and wolves",
        theme: "A book about bravery and finding courage when you feel small.",
        status: "Open",
    },
    {
        id: "WISH-002",
        age: 12,
        interests: "Fantasy, magic, and adventure",
        theme: "An escape to another world for a child going through a tough time at home.",
        status: "Open",
    },
];
